### ISSUE TITLE
PoPoLoCrois

### ISSUE THREAD

**Issue by chrisasma103** [jserodio/rg351p-ppsspp-settings#19]
At first, the game ran really slowly until I saw to add "retain changed textures", which helped a lot. It ran at around 25-30 fps, which is fine for a JRPG. However, I consistently run into an issue where after the first cutscene (Where Pietro's dad tells Pietro his mother is alive, and then the scene transition to when Pietro says he's going to go look for a cure), the game hits like 7 fps, then softlocks and crashes. On PPSSPP for windows, this issue doesn't occur. Any chance you could look into it and see if there's any kind of solution available? Thanks.

**Comment by jserodio** [comment]
No idea man I'm sorry. I'm closing the issue, please consider opening it on 💬[Discussions](https://github.com/jserodio/rg351p-ppsspp-settings/discussions) if you still did not find any solution. Maybe others found the right config for this game and can share it with you! 😘 Happy holidays and take care 🥂
