### ISSUE TITLE
FINAL FANTASY2  anniversary-edition

### ISSUE THREAD

**Issue by WSEC8097** [jserodio/rg351p-ppsspp-settings#2]
How to set up psp game ff2-anniversary-edition.

It seems not good working on world map.

**Comment by jserodio** [comment]
I'm willing to try this game out. Have you managed to solve your issue?

**Comment by WSEC8097** [comment]
I try to frame skipping 3 and auto frameskip check.

But sound is bad。

**Comment by jserodio** [comment]
感谢您报告错误

I will try it in some hours, maybe I can find a good configuration for you.

**Comment by jserodio** [comment]
There is a new version of 351elec out, the PSP emulator is new and performance has been increased, I need to check if something changed for this game.

**Comment by WSEC8097** [comment]
> There is a new version of 351elec out, the PSP emulator is new and performance has been increased, I need to check if something changed for this game.

Ok.
Thank you for your help.

**Comment by jserodio** [comment]
I don't think it still possible to add this game to the playable list.
It works fine on battles but the minimap lags are horrible sadly.

I'm closing the issue, I've made the Discussions available in this repository. Perhaps this is a better tool than using the Issues for this project. Feel free to contribute here:
https://github.com/jserodio/rg351p-ppsspp-settings/discussions/
