### ISSUE TITLE
Recommended settings for Hot Shots Golf 2 halved my FPS from default settings.

### ISSUE THREAD

**Issue by ArcadeDigger** [jserodio/rg351p-ppsspp-settings#9]
Recommended settings for Hot Shots Golf 2 (see linked below) halved my FPS from default settings.
https://github.com/jserodio/rg351p-ppsspp-settings/blob/main/settings/HOT%20SHOTS%20GOLF.md

Restarting the game added that screen turns black when starting a shot, only showing the power bar, which flickers.

**Comment by jserodio** [comment]
Basically:
- at 60 fps with frameskip 1 with autoframeskip ON > 60 fps when capable, 30 if not capable
- at 30 fps with frameskip 1 and autoframeskip ON > 30 fps when capable, 15 if not capable

When it's struggling, the frameskip will be used, 1 frame always halves the FPS.

The problem with this game is that shooting renders the game at 60 fps, and normal gameplay is at 30 fps.
So in this situation, it's recommended to use the frameskip ON.
I don't remember well but I think that if you had frameskip 0 setting, the shooting bar would be 60 fps but with a black screen.
And if you had frameskip 1, it would flicker, could you test it for me?

Regards.
